version: "3.3"
services:
  redis:
      container_name: chatapp-redis
      image: redis:alpine
      command: ["redis-server", "/etc/redis/redis.conf"]
      volumes:
        - ./redis.conf:/etc/redis/redis.conf
      expose:
        - "6379"
      ports:
        - "6379:6379"